name: firefast
description: "Firebase without the fuss. Define fields once, then just .write(), .read() Type-safe. Clean. Fast. Easy. Firestore, Realtime Database, Auth, Storage, Functions, Config and more!"
version: 0.1.6
homepage: https://github.com/jozzdart/firefast
repository: https://github.com/jozzdart/firefast
issue_tracker: https://github.com/jozzdart/firefast/issues
topics:
  - firebase
  - firestore
  - realtime
  - database
  - auth

environment:
  sdk: ">=3.5.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  limit: ^1.0.9
  cloud_firestore: ^5.6.6
  collection: ^1.19.1
  firebase_database: ^11.3.5
  firebase_remote_config: ^5.4.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_cloud_firestore: ^3.1.0
  firebase_database_mocks: ^0.7.1
  shrink: ^1.5.9
  shrink_flutter: ^0.0.4
