name: firefast
description: "Firebase without the fuss. Define fields once, then just .write(), .read() Type-safe. Clean. Fast. Easy. Firestore, Realtime Database, Auth, Storage, Functions, Config and more!"
version: 0.0.15
homepage: https://github.com/jozzzzep/firefast
repository: https://github.com/jozzzzep/firefast
issue_tracker: https://github.com/jozzzzep/firefast/issues
topics:
  - firebase
  - firestore
  - realtime
  - database
  - auth

environment:
  sdk: ^3.0.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.6
  collection: ^1.19.1
  firebase_database: ^11.3.5
  prf: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  test: ^1.25.15
  mockito: ^5.4.4
  build_runner: ^2.4.8
  fake_cloud_firestore: ^3.1.0
  firebase_database_mocks: ^0.7.1
