// Mocks generated by Mockito 5.4.4 from annotations
// in firefast/test/core/guards/guarded_operator_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i2;

import 'package:firefast/firefast_core.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [OperationGuard].
///
/// See the documentation for Mockito's code generation for more information.
class MockOperationGuard extends _i1.Mock implements _i3.OperationGuard {
  @override
  _i2.Future<bool> canPerform() => (super.noSuchMethod(
        Invocation.method(
          #canPerform,
          [],
        ),
        returnValue: _i2.Future<bool>.value(false),
        returnValueForMissingStub: _i2.Future<bool>.value(false),
      ) as _i2.Future<bool>);
}
